apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: t3-client
  namespace: demo
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: t3-client
        image: manojjahgirdar/client-application:v10.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: t3-client-service
  namespace: demo
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
  type: NodePort
