apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: client-application
  namespace: demo
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: client-application
        image: manojjahgirdar/client-application:v2.0
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: client-application-service
  namespace: demo
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
  type: NodePort

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: client-application-url
  namespace: demo
spec:
  path: /
  to:
    kind: Service
    name: client-application-service
  port:
    targetPort: 8080
